export const GET_USER_ACCOUNT_REQUEST = 'GET_USER_ACCOUNT_REQUEST'
export const GET_USER_ACCOUNT_SUCCESS = 'GET_USER_ACCOUNT_SUCCESS'
export const GET_USER_ACCOUNT_FAILURE = 'GET_USER_ACCOUNT_FAILURE'