export const GET_USER_ACCOUNT_REQUEST = 'GET_USER_ACCOUNT_REQUEST'
export const GET_USER_ACCOUNT_SUCCESS = 'GET_USER_ACCOUNT_SUCCESS'
export const GET_USER_ACCOUNT_FAILURE = 'GET_USER_ACCOUNT_FAILURE'

export const GET_LOCAL_USER_ACCOUNT_REQUEST = 'GET_LOCAL_USER_ACCOUNT_REQUEST'
export const GET_LOCAL_USER_ACCOUNT_SUCCESS = 'GET_LOCAL_USER_ACCOUNT_SUCCESS'
export const GET_LOCAL_USER_ACCOUNT_FAILURE = 'GET_LOCAL_USER_ACCOUNT_FAILURE'

export const VIEW_PROFILE_REQUEST = 'VIEW_PROFILE_REQUEST'
export const VIEW_PROFILE_SUCCESS = 'VIEW_PROFILE_SUCCESS'
export const VIEW_PROFILE_FAILURE = 'VIEW_PROFILE_FAILURE'

export const CLEAR_VIEW_PROFILE = 'CLEAR_VIEW_PROFILE';